### ISSUE TITLE
load conflicts with FileIO

### ISSUE THREAD

**Issue by davidanthoff** [jojal5/Extremes.jl#64]
Would it be possible to use a different name than `load` for the example datasets? `load` is used by FileIO.jl, and the entire Queryverse, and exporting that runs into lots of naming conflicts.

Maybe `dataset` might be a better name? And maybe not even export it?

**Comment by jojal5** [comment]
Thanks for the relevant suggestion. It will be implemented shortly.

**Comment by Balinus** [comment]
Closed by #65 

Thanks for the feedback @davidanthoff !

**Comment by davidanthoff** [comment]
Great, much appreciated!
