### ISSUE TITLE
Join efforts over ExtremeStats.jl?

### ISSUE THREAD

**Issue by juliohm** [jojal5/Extremes.jl#7]
Hi @jojal5 , learned about your package today. I wonder if you are interested in joining efforts in ExtremeStats.jl instead of working on a separate effort?

We have some user base already, and there is a lot of opportunity to improve the current estimators therein. Please let me know what you think, and we can plan details/improvements.

**Comment by jojal5** [comment]
Hi @juliohm, of course I would be interested to join effort. The next few weeks will be very crazy because of the university closing. I do not plan to work on the package before next sumnmer.

**Comment by juliohm** [comment]
Thank you for the follow up @jojal5 , if you can check the existing implementations in ExtremeStats.jl, and compare to what you have here, we can brainstorm improvements.

If you feel like working on extreme value theory a lot, please let me know and we can coordinate a more strategic plan of development.

**Comment by jojal5** [comment]
Ok I will check the existing implementations in ExtremeStats. 

I'm doing research in Extreme value theory, so I plan to develop an in-depth package.

**Comment by juliohm** [comment]
Awesome. Let's work over there then. I will send you an invitation to the organization if you are interested, and we can work on ideas there.

**Comment by juliohm** [comment]
@jojal5 I am closing this issue again given that you are spending time in a separate effort. Let me know if you change mind, it would be nice to contribute and learn from each other instead of duplicating functionality.

**Comment by jojal5** [comment]
Hi @juliohm. I'm still interested in collaborating and thanks for reminding me. At the moment, we are completing the structure of our package. In the short term, we will need development on clustering and plotting.

I had the impression that you were very busy with GeoStats.jl, a package that I use. Please tell me what is your proposition for beginning our collaboration.

**Comment by juliohm** [comment]
Hi @jojal5 I've sent you an invitation to join the JuliaEarth organization so that we can coordinate our efforts and discuss future directions of improvement. As soon as you accept the invitation, we can create a team to brainstorm what features are missing.

**Comment by juliohm** [comment]
@jojal5, thank you for accepting the invitation. Appreciate if you can make your membership public. I've created a team over there for us to discuss existing features and future plans. Can we close this issue and start planning over there?

**Comment by juliohm** [comment]
I scanned through the codebase and your functionality seems to be covered in ExtremeStats.jl, except the Bayes estimators. Can we move the discussion over there?

**Comment by jojal5** [comment]
I do not know if you look at all the development, especially in the branch dev, but we have so much more. We have notably probability weighted moment estimation, maximum likelihood estimation and Bayesian estimation for both stationary and non-stationary extreme-value models. Also, we provide thorough testing.

So no, most of our functionalities are not covered in ExtremeStats.jl. Also at this moment, I do not feel comfortable to transfer the package in the JuliaEarth repository. My team and I are doing research on Extreme-value theory and after an intern discussion, we want to keep the full control of our package.

**Comment by juliohm** [comment]
Sounds good. I didn't meant to insult your team's work. I am not supposed to know developments in other branches other than master, right? Anyways, sad this development is taking place in two places at the same time.
